// <auto-generated />
using System;
using CMCapital.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCapital.Persistence.Migrations
{
    [DbContext(typeof(CMCapitalDbContext))]
    [Migration("20250929161618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMCapital.Domain.Entities.TblCliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<DateTime?>("DthDelete")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Delete");

                    b.Property<DateTime>("DthInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Insert")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DthUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Update");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("UsuarioIdDelete")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUpdate")
                        .HasColumnType("int");

                    b.HasKey("ClienteId")
                        .HasName("TblCliente_pk");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ClienteId"), false);

                    b.HasIndex(new[] { "ClienteId" }, "TblCliente_ClienteId_index");

                    b.ToTable("TblCliente", (string)null);
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblProduto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime?>("DthDelete")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Delete");

                    b.Property<DateTime>("DthInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Insert")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DthUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Update");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdDelete")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUpdate")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId")
                        .HasName("TblProduto_pk");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ProdutoId"), false);

                    b.HasIndex(new[] { "ProdutoId" }, "TblProduto_ProdutoId_index");

                    b.ToTable("TblProduto", (string)null);
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DthDelete")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Delete");

                    b.Property<DateTime>("DthInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Insert")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DthUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Update");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UsuarioIdDelete")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUpdate")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId")
                        .HasName("TblUsuario_pk");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("UsuarioId"), false);

                    b.HasIndex(new[] { "UsuarioId" }, "TblUsuario_UsuarioId_index");

                    b.ToTable("TblUsuario", (string)null);
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblVendum", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DthDelete")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Delete");

                    b.Property<DateTime>("DthInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Insert")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DthUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTH_Update");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdDelete")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUpdate")
                        .HasColumnType("int");

                    b.HasKey("VendaId")
                        .HasName("TblVenda_pk");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VendaId"), false);

                    b.HasIndex(new[] { "ClienteId" }, "TblVenda_ClienteId_index");

                    b.HasIndex(new[] { "ProdutoId" }, "TblVenda_ProdutoId_index");

                    b.HasIndex(new[] { "VendaId" }, "TblVenda_VendaId_index");

                    b.ToTable("TblVenda");
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblVendum", b =>
                {
                    b.HasOne("CMCapital.Domain.Entities.TblCliente", "Cliente")
                        .WithMany("TblVenda")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("TblVenda_TblCliente_ClienteId_fk");

                    b.HasOne("CMCapital.Domain.Entities.TblProduto", "Produto")
                        .WithMany("TblVenda")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("TblVenda_TblProduto_ProdutoId_fk");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblCliente", b =>
                {
                    b.Navigation("TblVenda");
                });

            modelBuilder.Entity("CMCapital.Domain.Entities.TblProduto", b =>
                {
                    b.Navigation("TblVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
